#!/bin/bash

# Update installed packages.
#     Update installed brew packages.
#     Update installed gem packages.
#     Update installed npm packages.

# The MIT License (MIT)
#
# Copyright (c) 2014 Shohei KAMIMORI
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

source "$(dirname "${BASH_SOURCE}")"/imosh/imosh || exit 1
eval "${IMOSH_INIT}"

_update_brew() {
  if type "brew" >/dev/null 2>/dev/null; then
    echo 'Update brew packages.'
    brew update
    brew upgrade --all
    brew cleanup
  else
    echo 'Skipped.'
  fi
}

_update_gem() {
  if type "gem" >/dev/null 2>/dev/null; then
    echo 'Update gem packages.'
    if type "rubygems-update" >/dev/null 2>/dev/null; then
      gem install rubygems-update
    fi
    update_rubygems
    gem update
  else
    echo 'Skipped.'
  fi
}

_update_npm() {
  if type "npm" >/dev/null 2>/dev/null; then
    echo 'Update npm packages.'
    npm update --system
    npm update -g
  else
    echo 'Skipped.'
  fi
}

_update_all() {
  _update_brew
  _update_gem
  _update_npm
}

_update_all
